spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
