spring:
  application:
    name: seareport
  profiles:
    active: producao
  thymeleaf:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  config:
    import: optional:file:.env[.properties]

server:
  port: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    supported-submit-methods: ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
  api-docs:
    enabled: true
